language: cpp

before_install:
    # We need this line to have g++4.8 available in apt
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq gcc-4.8 g++-4.8
    # We want to compile with g++ 4.8 when rather than the default g++
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script:
  - make
  - ./mem_release_test
  - sudo ./sche -d0 -i0 -b0 -f1 -r2 -f3 -i0 -i0 -i0 -d0
